# Generated by Django 5.2.5 on 2025-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seats',
            new_name='number_of_seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='traveloption',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='traveloption',
            name='travel_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
